monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink bap_sink ]
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_.*"
      }
    ]
    actions = {
      update-props = {
        target.object = "unified-upmix"
        channelmix.upmix = true
        channelmix.upmix-method = psd
        channelmix.rear-delay = 12.0
        channelmix.mix-lfe = true
        channelmix.lfe-cutoff = 100
      }
    }
  }
]
