context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Unified Surround Upmix"
            audio.position = [ FL FR RL RR LFE ]
            capture.props = {
                node.name = "unified-upmix"
                media.class = Audio/Sink
                node.priority.driver = 1000
                node.priority.session = 1000
                channelmix.upmix = true
                channelmix.upmix-method = psd
                channelmix.rear-delay = 12.0
                channelmix.mix-lfe = true
                channelmix.lfe-cutoff = 80
            }
            playback.props = {
                node.name = "unified-upmix-output"
                audio.position = [ AUX0 AUX1 AUX4 AUX5 AUX3 ]
                target.object = "alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_X3_9E42D45FF9ACC811-03.pro-output-0"
                node.passive = true
                stream.dont-remix = true
            }
        }
    }
]