context.modules = [
    {
        name = libpipewire-module-vban-send
        args = {
            destination.ip = "opti.local"
            destination.port = 6980
            sess.name = "kubuntu-audio"
            sess.latency.msec = 20
            audio.format = "S16LE"     # S16LE for gaming (3.8Mbps). Upgrade: S24LE or S32LE for music
            audio.rate = 48000          # 48000 standard. 96000 for hi-res music
            audio.channels = 5
            audio.position = [ FL FR RL RR LFE ]
            stream.props = {
                node.name = "vban-sender"
                node.description = "Opti VBAN 5.1"
                node.nick = "Opti VBAN 5.1"
                media.class = "Audio/Sink"
                priority.session = 1000
                channelmix.upmix = true
                channelmix.upmix-method = psd
                channelmix.rear-delay = 12.0
                channelmix.mix-lfe = true
                channelmix.lfe-cutoff = 80
            }
        }
    }
]