context.modules = [
    {
        name = libpipewire-module-vban-send
        args = {
            destination.ip = "opti.local"
            destination.port = 6980
            sess.name = "kubuntu-audio"
            sess.latency.msec = 20
            audio.format = "S16LE"
            audio.rate = 48000
            audio.channels = 2
            audio.position = [ FL FR ]
            stream.props = {
                node.name = "vban-sender"
                node.description = "VBAN Sender to opti"
                media.class = "Audio/Sink"
            }
        }
    }
]