[Service]
ExecStartPre=/usr/bin/bash -c 'while ! grep -q "Sound Blaster X3" /proc/asound/cards 2>/dev/null; do sleep 0.5; done'
ExecStartPost=/usr/bin/bash -c 'sleep 2; pactl set-card-profile alsa_card.usb-Creative_Technology_Ltd_Sound_Blaster_X3_9E42D45FF9ACC811-03 pro-audio; amixer -c X3 sset Speaker 100%%; pactl set-default-sink unified-upmix'